Peak.create(name: "Everest", location: "Nepal, China", elevation: "8,848 meters")
Peak.create(name: "K2", location: "Pakistan, China", elevation: "8,614 meters")
Peak.create(name: "Kangchenjunga", location: "Nepal, India", elevation: "8,586 meters")
Peak.create(name: "Lhotse", location: "Nepal, China", elevation: "8,516 meters")
Peak.create(name: "Makalu", location: "Nepal, China", elevation: "8,485 meters")
Peak.create(name: "Cho Oyu", location: "Nepal, China", elevation: "8,188 meters")
Peak.create(name: "Dhaulagiri", location: "Nepal", elevation: "8,167 meters")
Peak.create(name: "Manaslu", location: "Nepal", elevation: "8,163 meters")
Peak.create(name: "Nanga Parbat", location: "Pakistan", elevation: "8,125 meters")
Peak.create(name: "Annapurna", location: "Nepal", elevation: "8,091 meters")
Peak.create(name: "Gasherbrum I", location: "Pakistan, China", elevation: "8,080 meters")
Peak.create(name: "Broad Peak", location: "Pakistan, China", elevation: "8,051 meters")
Peak.create(name: "Gasherbrum II", location: "Pakistan, China", elevation: "8,035 meters")
Peak.create(name: "Shishapangma", location: "China", elevation: "8,027 meters")